#mysql connector
spring:
  datasource:
    url: jdbc:mariadb://152.67.222.171:3306/bibimping2
    username: hello
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 8
      connection-timeout: 30000 # connection 획득 시도 후 실패 시 대기 시간

  session:
    store-type: redis

  data:
    redis:
      host: 152.67.222.171
      port: 6379
      password: password

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        http-only: true

  jpa:
    #hibernate:
      #ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace
