#mysql connector
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/bibimping2?useSSL=false&allowPublicKeyRetrieval=true
    username: hello
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 8
      connection-timeout: 30000 # connection 획득 시도 후 실패 시 대기 시간

  jpa:
    #hibernate:
    #ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      # show_sql: true
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace